# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Music-Image-Chord
version:      0.006
version_from: lib/Music/Image/Chord.pm
installdirs:  site
requires:
    Imager:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
